### ISSUE TITLE
Async/Await support 

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureStoragePersistence#14]
Connects to Particular/PlatformDevelopment#182

This is the AzureStoragePersistence adapter epic which incorporates the work for making the AzureStoragePersistence adapter async/await enabled. Please see [this blog post](http://particular.net/blog/async-await-its-time) about the reasoning behind it.

**Comment by DavidBoike** [comment]
There were no acceptance tests previously so current status is trying to add those and form a baseline with V5 before we go to V6.

Some of the existing tests may just be "Can only work with DTC" which is a nonstarter in Azure. We can't really change the V5 edition of the tests so we just have to note those and move on.

**Comment by DavidBoike** [comment]
Spent part of my day trying to figure out why the 3 tests in  When_doing_request_response_between_sagas were failing on the server but not locally on my machine. On the build server, apparently Type.GetType(name) is failing on every single one of those 3 tests, but not on all the other tests that pass and should be doing the exact same thing.

Coding in acceptance-testing branch, which is up-to-date.

**Comment by DavidBoike** [comment]
V5 acceptance tests down to 3 failures which are not worth attempting to fix. Pull #16 can now be considered to bring the acceptance tests into develop.
