### ISSUE TITLE
Upgrade Azure Storage Dependency to latest major range

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureStoragePersistence#21]
Upgrade to latest stable of the WindowsAzure.Storage dependency, range 6.0.0 to 7.0.0.

Note that some functionality that we use may have been obsoleted, and will cause a rewrite of certain functionality.

- [x] Timeouts and Subscription storages rely on TableServiceContext that is obsoleted  https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/5
- [x] Docs to include:
  - [x] Add configuration for TimeoutStateBlobName

**Comment by dbelcham** [comment]
Appears we need to address the following
- [ ]   TableServiceContext
- [ ]  TableServiceEntity
- [ ]  TableServiceQuery
