### ISSUE TITLE
Concurrently starting the same saga instance causes duplicate records to be stored

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.AzureStoragePersistence#26]
Since the persister has no way of enforcing uniqueness two messages starting the same saga will result in both of them succeeding and creating 2 "records" in storage. 

Following `Gets` will return [the first instance stored](https://github.com/Particular/NServiceBus.Azure/blob/master/src/NServiceBus.Azure/SagaPersisters/Azure/AzureSagaPersister.cs#L84) stored causing inconsistent business behavior.

Originally raised by @SimonCropp here: https://github.com/Particular/NServiceBus.Azure/issues/21

**Comment by andreasohlund** [comment]
During triage made by @andreasohlund, @udidahan and @yvesgoeleven it was decided to treat this one as critical and put out a patch immediately since this will lead to incorrect business behavior due to messages not being sent or messages being sent when they shouldn't have

cc @Particular/persistence-maintainers

**Comment by Scooletz** [comment]
This is fixed by: #32
