### ISSUE TITLE
StorageException not caught in TryGetTimeoutData

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStoragePersistence#36]
so here https://github.com/Particular/NServiceBus.AzureStoragePersistence/blob/develop/src/NServiceBus.AzureStoragePersistence/Timeout/TimeoutLogic/TimeoutPersister.cs#L348

we do

        bool TryGetTimeoutData(CloudTable timeoutDataTable, string partitionKey, string rowKey, out TimeoutDataEntity result)
        {
            result = (from c in timeoutDataTable.CreateQuery<TimeoutDataEntity>()
                      where c.PartitionKey == partitionKey && c.RowKey == rowKey // issue #191 cannot occur when both partitionkey and rowkey are specified
                      select c).ToList().SafeFirstOrDefault();

            return result != null;

        }

where `SafeFirstOrDefault` handles the possible storage exception https://github.com/Particular/NServiceBus.AzureStoragePersistence/blob/develop/src/NServiceBus.AzureStoragePersistence/SafeLinqExtensions.cs#L17

but `TryGetTimeoutData` does a `ToList` before calling `SafeFirstOrDefault` so the `StorageException` will be thrown outside the scope of `SafeFirstOrDefault`

**Comment by SimonCropp** [comment]
also why r we doing a tolist if we only need to check if a single one exists?

**Comment by SimonCropp** [comment]
SafeFirstOrDefault is used in a few places where is serves no purpose. eg `var future = futureTimeouts.SafeFirstOrDefault();` where futureTimeouts is an in memory list

**Comment by dbelcham** [comment]
If you don't to a `ToList` the Linq provider throws an error when `SafeFirstOrDefault` is executed. I'm not sure if this behavior was introduced when we moved to WAS v6.2, but the code did start throwing an exception in those situations (there are more than one location like this) when I was running the tests to verify that the move to WAS v6.2 was successful.

**Comment by SeanFeldman** [comment]
@dbelcham do you want to spike this together? It could be another case like [this](https://github.com/Azure/azure-storage-net/issues/232)

**Comment by Scooletz** [comment]
The `PR` #38 has been closed. Should this issue be closed as well then? /cc @dbelcham

**Comment by Scooletz** [comment]
Closing the issue as the PR has been merged.
