### ISSUE TITLE
Upgrade Storage Library to version 7.0.0

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStoragePersistence#53]
Connects to https://github.com/Particular/PlatformDevelopment/issues/729

With version 7.0.0 of the WindowsAzure.Storage library, we should package ASQ with it to allow customers to use version 7+, which they will be asking to allow them to use the latest MSFT library.

**Comment by SimonCropp** [comment]
done https://github.com/Particular/NServiceBus.AzureStoragePersistence/commit/700a87a7233fb430bf961408f3f481f89719c9ec
