### ISSUE TITLE
shouldnt LRUCache.items be a concurrent dictionary?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStoragePersistence#63]
instead locking everywhere?

**Comment by Scooletz** [comment]
Nope. The `LRUCache` uses two fields in every operation:
- `lru` list - to provide last recently used behavior
- `items` - to provide key-value mapping with O(1)

Locking everywhere ensures that these two parts can be updated atomically. 
`ConcurrentDictionary<,>` does not ensure lru behavior as it cannot remove the last item that was used.

If that answers your question, please close the issue. I'll create a PR with the comment above then to leave this information in the code itself.

**Comment by SimonCropp** [comment]
thanks
