### ISSUE TITLE
Use “NServiceBus/Persistence" as default connection string for Azure storage persisters

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStoragePersistence#8]
Currently  “NServiceBus/Persistence” is not used by Azure Storage persisters (`AzureSubscriptionStorageConfig`, `AzureSagaPersisterConfig`, `AzureTimeoutPersisterConfig`) as default connection string causing users to be confused ([Desk case for example](https://nservicebus.desk.com/agent/case/11715))

Also, this forces for scenarios where all persisters use the same storage account to define all three sections and replicate connection string for each.

**Comment by WilliamBZA** [comment]
I propose basing this on top of the work done [here](https://github.com/Particular/NServiceBus.AzureStoragePersistence/pull/33) as we can do some neater code with null instead of null and whitespace checks.
